warn/scrapers/mt.py
Update scraping strategy to address #233
=> Update MT to scraper Excel link from data page

warn/scrapers/ca.py
Address #119 and #120
- Only processes when there are new or changed files
- Removes obsolete files
- Handles current fiscal year Excel
- Handles historical PDFs
=> Fix CA current year bug and add support for scraping historical PDFs

.github/workflows/tests.yml, MANIFEST.in, setup.cfg, setup.py
=> Tidied up setup.py

.gitignore
=> Added vim patterns to gitignore

setup.py
This name mirrors the CLI tool, a step toward solving #247
=> Rename package as warn-scraper

tests/test_job_center.py
=> Sort lists prior to comparison in test_cached_search_results

.github/workflows/tests.yml, Pipfile, Pipfile.lock, setup.py
=> Add flake8 to the dev dependencies and the Action-based testing

Makefile, Pipfile, Pipfile.lock
Fixes #225 
Contributes to #263
=> Added test coverage option to Makefile

Makefile
=> Added flake8 command to Makefile

Makefile
=> Added docs command to Makefile

.github/workflows/tests.yml, Pipfile, Pipfile.lock
=> Flake8 tests for docstrings

Pipfile, Pipfile.lock, docs/contributing.rst, docs/usage.md, setup.py, warn/__main__.py, warn/runner.py
=> Cut bln-etl

.github/workflows/tests.yml
=> Added PyPI deploy action job for tagged releases

warn/utils.py
Should cover https://github.com/biglocalnews/warn-scraper/issues/320
=> Ensure directories are created before trying to write them.

Pipfile, Pipfile.lock, docs/conf.py, docs/index.rst, docs/reference.rst, warn/cache.py
=> Add Cache class autodocs to the documentation site

warn/runner.py, warn/scrapers/mt.py, warn/utils.py
=> Refactor MT scraper to skip pandas

warn/scrapers/ny.py
=> Remove pandas from NY scrape

warn/scrapers/or.py
=> Refactor OR scraper to not use pandas

warn/scrapers/nj.py
=> Cut pandas dedupe from NJ scrape

warn/scrapers/tx.py
=> Reworked TX scrape to not use pandas

Pipfile, Pipfile.lock, setup.py
=> Remove pandas requirement

Makefile, docs/reference.rst
=> Add Makefile docs

warn/utils.py
=> Add user-agent to requests

docs/reference.rst, warn/utils.py
=> Add docs for warn.utils

warn/scrapers/ak.py, warn/scrapers/al.py, warn/scrapers/az.py, warn/scrapers/ca.py, warn/scrapers/co.py, warn/scrapers/ct.py, warn/scrapers/dc.py, warn/scrapers/de.py, warn/scrapers/fl.py, warn/scrapers/ga.py, warn/scrapers/in.py, warn/scrapers/ks.py, warn/scrapers/md.py, warn/scrapers/me.py, warn/scrapers/mo.py, warn/scrapers/mt.py, warn/scrapers/ne.py, warn/scrapers/nj.py, warn/scrapers/ny.py, warn/scrapers/oh.py, warn/scrapers/ok.py, warn/scrapers/or.py, warn/scrapers/ri.py, warn/scrapers/sd.py, warn/scrapers/tx.py, warn/scrapers/ut.py, warn/scrapers/va.py, warn/scrapers/vt.py, warn/scrapers/wa.py, warn/scrapers/wi.py
=> Added __tags__ dunder to all scrapers

warn/scrapers/ca.py, warn/scrapers/co.py, warn/scrapers/va.py, warn/utils.py
=> Deprecate `download_file` util

warn/scrapers/oh.py
=> Tidy OH scrape

warn/scrapers/in.py
=> Tidy IN scraper

warn/scrapers/ri.py
=> Tidy RI scrape

warn/scrapers/ut.py
=> Tidy UT scrape

warn/scrapers/sd.py
=> Tidy SD scrape

.github/workflows/continuous-deployment.yml, .pre-commit-config.yaml, Makefile, Pipfile, Pipfile.lock, docs/reference.rst, setup.py, warn/scrapers/ga.py, warn/scrapers/tx.py, warn/utils.py
Fixes #376 and also adds a job to our Action testing
=> Add static type checking with mypy

.github/workflows/continuous-deployment.yml, Makefile
=> Add coverage to testing

warn/scrapers/md.py
=> Refactored MD to use writing utility

warn/scrapers/dc.py
=> Tidy DC scraper

warn/scrapers/ne.py
A little clean up done as a side quest while pursuing #331. @zstumgoren, I could use a review here when you have time.
=> Tidy NE scrape

warn/scrapers/mo.py
For #331. Also gets the 2022 page in the scrape.
=> Tidy MO scraper

warn/scrapers/wa.py, warn/utils.py
For #331.
Having trouble getting the session request to work consistently. I'm getting "connection reset by peer" errors from the server. Unclear if this something I've caused, or if it was a pre-existing bug. Defer to @zstumgoren on the background.
=> Tidy WA scraper

docs/contributing.rst, warn/platforms/job_center/utils.py, warn/scrapers/ak.py, warn/scrapers/al.py, warn/scrapers/ct.py, warn/scrapers/dc.py, warn/scrapers/ga.py, warn/scrapers/ia.py, warn/scrapers/in.py, warn/scrapers/md.py, warn/scrapers/mo.py, warn/scrapers/mt.py, warn/scrapers/nj.py, warn/scrapers/ny.py, warn/scrapers/oh.py, warn/scrapers/or.py, warn/scrapers/ri.py, warn/scrapers/sd.py, warn/scrapers/tx.py, warn/scrapers/ut.py, warn/scrapers/va.py, warn/scrapers/wa.py, warn/scrapers/wi.py, warn/utils.py
=> Flip inputs to write_rows_to_csv so that they match every other function

warn/platforms/job_center/utils.py
=> Fix jobcenter pathing

docs/sources.md, warn/scrapers/nm.py
Patterned on #370 before it got [complicated](https://www.youtube.com/watch?v=5NPBIwQyPWE).
```sh
python -m warn.cli NM -l DEBUG
```
=> Add NM scraper

docs/sources.md, warn/scrapers/la.py
Getting on the board in the home of the Big Easy while [Chi-Town rests](https://github.com/biglocalnews/warn-scraper/pull/358).
```sh
python -m warn.cli LA -l DEBUG
```
Closes #79
=> Add LA scraper

warn/scrapers/tx.py
=> Fixed duplicate header bug in Texas

warn/cli.py
=> Convert CLI path imports into Path objects

.pre-commit-config.yaml
=> Added flake8 extras to pre-commit

warn/scrapers/dc.py
=> Correct DC scraper cache prefix from md/

warn/scrapers/ri.py
=> Fix RI scraper

warn/scrapers/ct.py
=> CT hack needs a continue to work. 

warn/scrapers/nj.py
Fixes #402 and a fresh bug I never filed an issue on.
=> Switched NJ to use an Excel sheet

warn/cache.py, warn/utils.py
Tries to DRY this (and all subsequent modifications) by using the util get_url method in the cache download method.
Closes #424
=> Use BLN user-agent when downloading

warn/scrapers/oh.py
=> Get HTML archival pages for OH

warn/scrapers/ca.py
State left an extra space, got 404
Closes #423
=> Trim URL to fix missing PDF in CA

warn/scrapers/il.py
Add Excel-only scraper for IL. Also downloads PDFs, contains skeleton code to parse them.
```sh
python -m warn.cli IL -l DEBUG
```
Closes #81.
=> Add IL Excel scraper

docs/sources.md, warn/scrapers/il.py
Goes back to year I was born/year WARN passed, seems like a lot less trouble?
Closes #431
=> Use IL's DB export

warn/scrapers/dc.py
Improves on the hack for #238 by now using the mostly-correct links from the agency site, but patching in an Archive.org URL for 2014 only if the URL for 2018 continues to match (sunsetting the hack if the agency corrects this). This expands the list of years we scrape. Also filters out an empty row and corrects a reference to `md` in the cache key.
=> fix(dc): use archive for 2014, links for others

warn/scrapers/oh.py
Parses PDFs going back to 2015 from the Ohio WARN website.
```sh
python -m warn.cli oh
```
Closes #72
=> Parse historical OH PDFs

.github/workflows/continuous-deployment.yml, .pre-commit-config.yaml, Pipfile, Pipfile.lock, docs/sources.md
=> Cut Python 3.7 hacks

warn/scrapers/ga.py
=> Expand GA date range to cover 1989

warn/scrapers/ca.py
The excel headers changed on us. I also cut a bunch of the caching code here for simplicity and readability.
Fixes #463
=> Fix CA excel headers

warn/scrapers/ca.py
They are farting around with the column headers again.
=> Another CA fix

warn/scrapers/mi.py
I coded the mi scraper and applied corrections.
=> MI scraper

warn/scrapers/ca.py
=> Fix CA jobs number

warn/scrapers/ca.py
=> Another fix for the CA Excel stuff

warn/scrapers/ny.py
=> Added an HTML scraper for NY's most recent data that merges with the existing historical Excel file

warn/cache.py, warn/scrapers/ia.py
=> Make sure the IA urls have the domain

warn/scrapers/ca.py
=> Strict parsing of PDF headers in Calif. 

warn/scrapers/ca.py
=> More durable fix for CA header index order changes

warn/scrapers/sc.py
=> Fix SC url and href parsing

warn/scrapers/hi.py
Scraper will break, transformer will come back.
=> Back out #600 for now

warn/scrapers/co.py
Testing with
csvcut -n co-old.csv to get a list of columns
workforce_region
jobs
location
occupations
permanent_job_losses
dropdown
letter
naics
end_date
email
at_the_location
contact
fein
notice_date
temporary_job_losses
company
received_date
reason
begin_date
reduced_hours
furloughs
phone
workforce_area
workforce_region,jobs,location,occupations,permanent_job_losses,dropdown,letter,naics,end_date,email,at_the_location,contact,fein,notice_date,temporary_job_losses,company,received_date,reason,begin_date,reduced_hours,furloughs,phone,workforce_area
csvsort co-old.csv >csv-old-sorted.csv
csvcut -c workforce_region,jobs,location,occupations,permanent_job_losses,dropdown,letter,naics,end_date,email,at_the_location,contact,fein,notice_date,temporary_job_losses,company,received_date,reason,begi …
=> Patch CO scraper
